---
- name: Desplegar stack Node + PostgreSQL
  hosts: dev
  become: yes

  tasks:
    - name: Instalar Docker y Docker Compose
      apt:
        name: ["docker.io", "docker-compose"]
        state: present
        update_cache: yes

    - name: Crear carpeta del proyecto
      file:
        path: /home/ubuntu/node-postgres-compose
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copiar archivos del proyecto
      copy:
        src: node-postgres-compose/
        dest: /home/ubuntu/node-postgres-compose/
        owner: ubuntu
        group: ubuntu
        mode: '0755'
